# Main build settings
[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# KV store configuration
[functions]
  [functions.build_status_store]
  name = "build_status_store"
  description = "Stores the current build status of the application."

# Build hook processing
[build.processing]
  [build.processing.on-prebuild]
    command = "node scripts/set-building.js"
  
  [build.processing.on-success]
    command = "node scripts/set-ready.js"

  [build.processing.on-error]
    command = "node scripts/set-ready.js"