# Main build settings
[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# This section tells Netlify to give your functions access to the blob store.
[[functions]]
  name = "build-status" # The serverless function that clients poll
  [functions.blobs]
    store = "build_status_store"

[[functions]]
  name = "set-building" # A name for your build hook script
  [functions.blobs]
    store = "build_status_store"

[[functions]]
  name = "set-ready" # A name for your build hook script
  [functions.blobs]
    store = "build_status_store"

# Build hook processing
[build.processing]
  [build.processing.on-prebuild]
    command = "node scripts/set-building.js"
  
  [build.processing.on-success]
    command = "node scripts/set-ready.js"

  [build.processing.on-error]
    command = "node scripts/set-ready.js"